#!/usr/bin/env bash
# Automatic S3 background sync setup script.
# Saved at /home/ubuntu/s3-mount/cloud-machine-setup/s3_auto_sync_setup.sh

set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}======================================================${NC}"
echo -e "${BLUE}     S3 BACKGROUND AUTOMATIC SYNC INSTALLER           ${NC}"
echo -e "${BLUE}======================================================${NC}"

# Check for AWS CLI
if ! command -v aws &> /dev/null; then
  echo -e "${RED}Error: AWS CLI is not installed. Please run s3_mount_setup.sh first to install it.${NC}"
  exit 1
fi

# Step 1: Get Local Directory
read -rp "Enter the local directory to watch/sync (default: /home/ubuntu/geophysical-multi-model-agentic-ai): " LOCAL_DIR
LOCAL_DIR="${LOCAL_DIR:-/home/ubuntu/geophysical-multi-model-agentic-ai}"
eval LOCAL_DIR="$LOCAL_DIR"

if [ ! -d "$LOCAL_DIR" ]; then
  echo -e "${RED}Error: Local directory $LOCAL_DIR does not exist.${NC}"
  exit 1
fi

# Step 2: Get S3 Bucket & Prefix
read -rp "Enter the S3 Bucket Name (default: agentic-paper-s3): " BUCKET_NAME
BUCKET_NAME="${BUCKET_NAME:-agentic-paper-s3}"

read -rp "Enter the S3 Destination Prefix/Folder (default: geophysical-multi-model-agentic-ai, use '.' for bucket root): " S3_PREFIX
S3_PREFIX="${S3_PREFIX:-geophysical-multi-model-agentic-ai}"

if [ "$S3_PREFIX" = "." ]; then
  S3_PATH="s3://$BUCKET_NAME"
else
  S3_PATH="s3://$BUCKET_NAME/$S3_PREFIX"
  
fi

# Step 3: Verify Access
echo -e "\nVerifying S3 connectivity to $S3_PATH ..."
if aws s3 ls "s3://$BUCKET_NAME" > /dev/null 2>&1; then
  echo -e "${GREEN}Success! S3 permissions verified.${NC}"
else
  echo -e "${RED}Access Denied or Bucket Not Found. Please attach the correct IAM role or check bucket name.${NC}"
  exit 1
fi

# Step 4: Configure the Cron Job
echo -e "\nConfiguring background cron job (runs every minute)..."

RUNNER_SCRIPT="$(cd "$(dirname "$0")" && pwd)/s3_sync_run.sh"

echo "Creating background sync runner script at $RUNNER_SCRIPT ..."
cat << EOF > "$RUNNER_SCRIPT"
#!/usr/bin/env bash
# Background S3 sync runner generated by s3_auto_sync_setup.sh

LOCAL_DIR="$LOCAL_DIR"
S3_PATH="$S3_PATH"

# Prevent concurrent runs of this script using flock
LOCK_FILE="/tmp/s3_sync_\$(echo -n "\$LOCAL_DIR" | md5sum | cut -d' ' -f1).lock"
exec 9>"\$LOCK_FILE"
if ! flock -n 9; then
  exit 0
fi

# Dynamic date components for nested logging
YEAR=\$(date +%Y)
MONTH=\$(date +%m)
DAY=\$(date +%d)
HOUR=\$(date +%H)
TIMESTAMP=\$(date +%Y-%m-%d_%H-%M-%S)

LOG_DIR="\$HOME/s3_sync_logs/\$YEAR/\$MONTH/\$DAY/\$HOUR"
mkdir -p "\$LOG_DIR"

echo "=== S3 Sync Start: \$(date) ===" > "\$LOG_DIR/\${TIMESTAMP}.log"
aws s3 sync "\$LOCAL_DIR" "\$S3_PATH" --exclude ".venv/*" --delete >> "\$LOG_DIR/\${TIMESTAMP}.log" 2>&1
echo "=== S3 Sync End: \$(date) ===" >> "\$LOG_DIR/\${TIMESTAMP}.log"
EOF

chmod +x "$RUNNER_SCRIPT"

# Construct the cron command line to run the runner script
CRON_CMD="* * * * * $RUNNER_SCRIPT >/dev/null 2>&1"

# Read existing crontab
CURRENT_CRON=$(crontab -l 2>/dev/null || echo "")

# Prevent duplicate cron jobs
if echo "$CURRENT_CRON" | grep -Fq "$RUNNER_SCRIPT" || echo "$CURRENT_CRON" | grep -Fq "aws s3 sync $LOCAL_DIR"; then
  echo -e "${YELLOW}An automatic sync cron job for this directory/runner is already registered. Updating it...${NC}"
  # Remove the old one
  CURRENT_CRON=$(echo "$CURRENT_CRON" | grep -Fv "$RUNNER_SCRIPT" | grep -Fv "aws s3 sync $LOCAL_DIR" || true)
fi

# Write the new crontab
NEW_CRON=$(echo -e "${CURRENT_CRON}\n${CRON_CMD}" | sed '/^$/d')
echo "$NEW_CRON" | crontab -

echo -e "\n${GREEN}======================================================${NC}"
echo -e "${GREEN} Background Auto-Sync setup complete!${NC}"
echo -e " Local directory: ${BLUE}$LOCAL_DIR${NC}"
echo -e " S3 destination:  ${BLUE}$S3_PATH${NC}"
echo -e " Log directory:   ${BLUE}~/s3_sync_logs/YYYY/MM/DD/HH/${NC}"
echo -e " Interval:        ${YELLOW}Every minute (silent in background)${NC}"
echo -e "${GREEN}======================================================${NC}"
